name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy Using SSH On Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd account-pr
          sudo apt update
          sudo apt install gunicorn -y
          python3 -m pip install --upgrade pip
          sudo fuser -k 443/tcp
          sudo killall gunicorn
          sudo rm -rf projectrexa-accounts
          git clone git@github.com:Om-Mishra7/projectrexa-accounts.git
          cd projectrexa-accounts
          sudo pip install -r requirements.txt
          sudo nohup gunicorn --certfile='/etc/letsencrypt/live/accounts.projectrexa.dedyn.io/fullchain.pem' --keyfile='/etc/letsencrypt/live/accounts.projectrexa.dedyn.io/privkey.pem' -w 4 -b 0.0.0.0:443 run:app > gunicorn.log 2>&1 &

      
